- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: 18  # 从22改为18

- name: Setup pnpm
  uses: pnpm/action-setup@v4
  with:
    version: 8  # 从9改为8

- name: 配置npm镜像
  run: npm config set registry https://registry.npmmirror.com

- name: Install dependencies
  working-directory: ./vela-src
  run: pnpm install --no-frozen-lockfile
