name: Build Windows Vela
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm via npm
        run: npm install -g pnpm

      # 配置node-gyp使用系统自带的VS编译工具，不需要安装windows-build-tools
      - name: Configure node-gyp
        run: |
          npm config set msvs_version 2022
          npm config set python python3

      - name: Install dependencies
        run: pnpm install

      - name: Build Windows
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vela-Windows-Build
          path: dist/*.exe
